### ISSUE TITLE
Got a 0-length file

### ISSUE THREAD

**Issue by ambs** [rwstauner/Pod-Markdown#12]
Hello

`````
$ perldoc -o Markdown lib/Math/KullbackLeibler/Discrete.pm > README.md
Got a 0-length file from lib/Math/KullbackLeibler/Discrete.pm via Pod::Markdown!?

 at /opt/perl/bin/perldoc line 9.
`````

it would be cool if Pod::markdown worked well with perldoc -o option. :-)

**Comment by rwstauner** [comment]
version 3.000 has been released and works with `perldoc -o`.
Thanks for reporting, I didn't even know about `perldoc -o` :)
