### ISSUE TITLE
Issue with UTF-8

### ISSUE THREAD

**Issue by jonasbn** [rwstauner/Pod-Markdown#14]
I observe the following issue:

``` 
Wide character in print at /Users/jonasbn/.perlbrew/libs/perl-5.20.2@module-build-bundle/lib/perl5/Pod/Markdown.pm line 347, <$fh> line 737.
```

When using `pod2markdown`, I tried with @ambs fork, but this does not handle the above situation :-/

**Comment by rwstauner** [comment]
Sorry.
I got a couple of emails early this year about a few encoding bugs and it took me a while to get a chance to work on them.
I finally got to it in the last few months and I'm about 95% done with some encoding changes (and the `-o` fix).
Saturday mornings are usually my chance to catch up on stuff, so I'll do my best to wrap it up tomorrow and have a release out shortly.

**Comment by rwstauner** [comment]
version 3.000 has been released and addresses this issue.
