### ISSUE TITLE
Better support for links to modules that are not on CPAN (e.g. modules internal to a project)

### ISSUE THREAD

**Issue by drmuey** [rwstauner/Pod-Markdown#16]
Details at https://rt.cpan.org/Ticket/Display.html?id=120452

**Comment by karenetheridge** [comment]
this issue can be closed as the RT is resolved.

**Comment by rwstauner** [comment]
thanks, i missed this.

resolved in 8cfc493e34b3384980544769ba3257cc678ab5c5
