### ISSUE TITLE
set man_url_prefix from pod2markdown

### ISSUE THREAD

**Issue by josch** [rwstauner/Pod-Markdown#24]
Hi,

please consider adding an option to `pod2markdown` that allows changing the default man.he.net/ to something else.

Thank you!

**Comment by rwstauner** [comment]
I would gladly accept a pull request for this feature

**Comment by josch** [comment]
Uh nice! How would you like this option to be named? Should it be `--man-url-prefix`?

**Comment by rwstauner** [comment]
Yes, matching the existing attribute names keeps things nice and simple.  Thanks!

**Comment by rwstauner** [comment]
Let me know if you have any questions.  I had forgotten the option was already present in the lib, so it probably just needs an entry in the GetOpts list to make it available to the CLI: https://github.com/rwstauner/Pod-Markdown/blob/514edd059beb56a7a7263cfc6ad15719d417e988/bin/pod2markdown#L18-L19
